using System.Collections.Generic;

namespace ORMPerformanceTest.TestData.Helpers
{
    internal static class CityData
    {
        public static IEnumerable<string> City()
        {
            yield return "Aleksandrów Kujawski";
            yield return "Aleksandrów Łódzki";
            yield return "Alwernia (MP)";
            yield return "Andrychów (MP)";
            yield return "Annopol (LB)";
            yield return "Augustów (PL)";
            yield return "Babimost (LS)";
            yield return "Baborów (OP)";
            yield return "Baranów Sandomierski (PK)";
            yield return "Barcin (KP)";
            yield return "Barczewo (WM)";
            yield return "Bardo (DŚ)";
            yield return "Barlinek (ZP)";
            yield return "Bartoszyce (WM)";
            yield return "Barwice (ZP)";
            yield return "Bełchatów (ŁD)";
            yield return "Bełżyce (LB)";
            yield return "Będzin (ŚL)";
            yield return "Biała (OP)";
            yield return "Biała Piska (WM)";
            yield return "Biała Podlaska (LB)";
            yield return "Biała Rawska (ŁD)";
            yield return "Białobrzegi (MZ)";
            yield return "Białogard (ZP)";
            yield return "Biały Bór (ZP)";
            yield return "Białystok (PL)";
            yield return "Biecz (MP)";
            yield return "Bielawa (DŚ)";
            yield return "Bielsk Podlaski (PL)";
            yield return "Bielsko-Biała (ŚL)";
            yield return "Bieruń (ŚL)";
            yield return "Bierutów (DŚ)";
            yield return "Bieżuń (MZ)";
            yield return "Biłgoraj (LB)";
            yield return "Biskupiec (WM)";
            yield return "Bisztynek (WM)";
            yield return "Blachownia (ŚL)";
            yield return "Błaszki (ŁD)";
            yield return "Błażowa (PK)";
            yield return "Błonie (MZ)";
            yield return "Bobolice (ZP)";
            yield return "Bobowa (MP)";
            yield return "Bochnia (MP)";
            yield return "Bodzentyn (ŚK)";
            yield return "Bogatynia (DŚ)";
            yield return "Boguchwała (PK)";
            yield return "Boguszów-Gorce (DŚ)";
            yield return "Bojanowo (WP)";
            yield return "Bolesławiec (DŚ)";
            yield return "Bolków (DŚ)";
            yield return "Borek Wielkopolski (WP)";
            yield return "Borne Sulinowo (ZP)";
            yield return "Braniewo (WM)";
            yield return "Brańsk (PL)";
            yield return "Brodnica (KP)";
            yield return "Brok (MZ)";
            yield return "Brusy (PM)";
            yield return "Brwinów (MZ)";
            yield return "Brzeg (OP)";
            yield return "Brzeg Dolny (DŚ)";
            yield return "Brzesko (MP)";
            yield return "Brzeszcze (MP)";
            yield return "Brześć Kujawski (KP)";
            yield return "Brzeziny (ŁD)";
            yield return "Brzostek (PK)";
            yield return "Brzozów (PK)";
            yield return "Buk (WP)";
            yield return "Bukowno (MP)";
            yield return "Busko-Zdrój (ŚK)";
            yield return "Bychawa (LB)";
            yield return "Byczyna (OP)";
            yield return "Bydgoszcz (KP)";
            yield return "Bystrzyca Kłodzka (DŚ)";
            yield return "Bytom (ŚL)";
            yield return "Bytom Odrzański (LS)";
            yield return "Bytów (PM)";
            yield return "Cedynia (ZP)";
            yield return "Chełm (LB)";
            yield return "Chełmek (MP)";
            yield return "Chełmno (KP)";
            yield return "Chełmża (KP)";
            yield return "Chęciny (ŚK)";
            yield return "Chmielnik (ŚK)";
            yield return "Chocianów (DŚ)";
            yield return "Chociwel (ZP)";
            yield return "Chodecz (KP)";
            yield return "Chodzież (WP)";
            yield return "Chojna (ZP)";
            yield return "Chojnice (PM)";
            yield return "Chojnów (DŚ)";
            yield return "Choroszcz (PL)";
            yield return "Chorzele (MZ)";
            yield return "Chorzów (ŚL)";
            yield return "Choszczno (ZP)";
            yield return "Chrzanów (MP)";
            yield return "Ciechanowiec (PL)";
            yield return "Ciechanów (MZ)";
            yield return "Ciechocinek (KP)";
            yield return "Cieszanów (PK)";
            yield return "Cieszyn (ŚL)";
            //yield return "Ciężkowice (MP)";
            //yield return "Cybinka (LS)";
            //yield return "Czaplinek (ZP)";
            //yield return "Czarna Białostocka (PL)";
            //yield return "Czarna Woda (PM)";
            //yield return "Czarne (PM)";
            //yield return "Czarnków (WP)";
            //yield return "Czchów (MP)";
            //yield return "Czechowice-Dziedzice (ŚL)";
            //yield return "Czeladź (ŚL)";
            //yield return "Czempiń (WP)";
            //yield return "Czerniejewo (WP)";
            //yield return "Czersk (PM)";
            //yield return "Czerwieńsk (LS)";
            //yield return "Czerwionka-Leszczyny (ŚL)";
            //yield return "Częstochowa (ŚL)";
            //yield return "Człopa (ZP)";
            //yield return "Człuchów (PM)";
            //yield return "Czyżew (PL)";
            //yield return "Ćmielów (ŚK)";
            //yield return "Daleszyce (ŚK)";
            //yield return "Darłowo (ZP)";
            //yield return "Dąbie (WP)";
            //yield return "Dąbrowa Białostocka (PL)";
            //yield return "Dąbrowa Górnicza (ŚL)";
            //yield return "Dąbrowa Tarnowska (MP)";
            //yield return "Debrzno (PM)";
            //yield return "Dębica (PK)";
            //yield return "Dęblin (LB)";
            //yield return "Dębno (ZP)";
            //yield return "Dobczyce (MP)";
            //yield return "Dobiegniew (LS)";
            //yield return "Dobra (powiat łobeski) (ZP";
            //yield return "Dobra (powiat turecki) (WP";
            //yield return "Dobre Miasto (WM)";
            //yield return "Dobrodzień (OP)";
            //yield return "Dobrzany (ZP)";
            //yield return "Dobrzyń nad Wisłą (KP)";
            //yield return "Dolsk (WP)";
            //yield return "Drawno (ZP)";
            //yield return "Drawsko Pomorskie (ZP)";
            //yield return "Drezdenko (LS)";
            //yield return "Drobin (MZ)";
            //yield return "Drohiczyn (PL)";
            //yield return "Drzewica (ŁD)";
            //yield return "Dukla (PK)";
            //yield return "Duszniki-Zdrój (DŚ)";
            //yield return "Dynów (PK)";
            //yield return "Działdowo (WM)";
            //yield return "Działoszyce (ŚK)";
            //yield return "Działoszyn (ŁD)";
            //yield return "Dzierzgoń (PM)";
            //yield return "Dzierżoniów (DŚ)";
            //yield return "Dziwnów (ZP)";
            //yield return "Elbląg (WM)";
            //yield return "Ełk (WM)";
            //yield return "Frampol (LB)";
            //yield return "Frombork";
            //yield return "Garwolin (MZ)";
            //yield return "Gąbin (MZ)";
            //yield return "Gdańsk (PM)";
            //yield return "Gdynia (PM)";
            //yield return "Giżycko (WM)";
            //yield return "Glinojeck (MZ)";
            //yield return "Gliwice (ŚL)";
            //yield return "Głogów (DŚ)";
            //yield return "Głogów Małopolski (PK)";
            //yield return "Głogówek (OP)";
            //yield return "Głowno (ŁD)";
            //yield return "Głubczyce (OP)";
            //yield return "Głuchołazy (OP)";
            //yield return "Głuszyca (DŚ)";
            //yield return "Gniew (PM)";
            //yield return "Gniewkowo (KP)";
            //yield return "Gniezno (WP)";
            //yield return "Gogolin (OP)";
            //yield return "Golczewo (ZP)";
            //yield return "Goleniów (ZP)";
            //yield return "Golina (WP)";
            //yield return "Golub-Dobrzyń (KP)";
            //yield return "Gołańcz (WP)";
            //yield return "Gołdap (WM)";
            //yield return "Goniądz (PL)";
            //yield return "Gorlice (MP)";
            //yield return "Gorzów Śląski (OP)";
            //yield return "Gorzów Wielkopolski (LS)";
            //yield return "Gostynin (MZ)";
            //yield return "Gostyń (WP)";
            //yield return "Gościno (ZP)";
            //yield return "Gozdnica (LS)";
            //yield return "Góra (DŚ)";
            //yield return "Góra Kalwaria (MZ)";
            //yield return "Górowo Iławeckie (WM)";
            //yield return "Górzno (KP)";
            //yield return "Grabów nad Prosną (WP)";
            //yield return "Grajewo (PL)";
            //yield return "Grodków (OP)";
            //yield return "Grodzisk Mazowiecki (MZ)";
            //yield return "Grodzisk Wielkopolski (WP)";
            //yield return "Grójec (MZ)";
            //yield return "Grudziądz (KP)";
            //yield return "Grybów (MP)";
            //yield return "Gryfice (ZP)";
            //yield return "Gryfino (ZP)";
            //yield return "Gryfów Śląski (DŚ)";
            //yield return "Gubin (LS)";
            //yield return "Hajnówka (PL)";
            //yield return "Halinów (MZ)";
            //yield return "Hel (PM)";
            //yield return "Hrubieszów";
            //yield return "Iława (WM)";
            //yield return "Iłowa (LS)";
            //yield return "Iłża (MZ)";
            //yield return "Imielin (ŚL)";
            //yield return "Inowrocław (KP)";
            //yield return "Ińsko (ZP)";
            //yield return "Iwonicz-Zdrój (PK)";
            //yield return "Izbica Kujawska (KP)";
            //yield return "Jabłonowo Pomorskie (KP)";
            //yield return "Janikowo (KP)";
            //yield return "Janowiec Wielkopolski (KP)";
            //yield return "Janów Lubelski (LB)";
            //yield return "Jarocin (WP)";
            //yield return "Jarosław (PK)";
            //yield return "Jasień (LS)";
            //yield return "Jasło (PK)";
            //yield return "Jastarnia (PM)";
            //yield return "Jastrowie (WP)";
            //yield return "Jastrzębie-Zdrój (ŚL)";
            //yield return "Jawor (DŚ)";
            //yield return "Jaworzno (ŚL)";
            //yield return "Jaworzyna Śląska (DŚ)";
            //yield return "Jedlicze (PK)";
            //yield return "Jedlina-Zdrój (DŚ)";
            //yield return "Jedwabne (PL)";
            //yield return "Jelcz-Laskowice (DŚ)";
            //yield return "Jelenia Góra (DŚ)";
            //yield return "Jeziorany (WM)";
            //yield return "Jędrzejów (ŚK)";
            //yield return "Jordanów (MP)";
            //yield return "Józefów (powiat biłgorajsk";
            //yield return "Józefów (powiat otwocki) (";
            //yield return "Jutrosin (WP)";
            //yield return "Kalety (ŚL)";
            //yield return "Kalisz (WP)";
            //yield return "Kalisz Pomorski (ZP)";
            //yield return "Kalwaria Zebrzydowska (MP)";
            //yield return "Kałuszyn (MZ)";
            //yield return "Kamienna Góra (DŚ)";
            //yield return "Kamień Krajeński (KP)";
            //yield return "Kamień Pomorski (ZP)";
            //yield return "Kamieńsk (ŁD)";
            //yield return "Kańczuga (PK)";
            //yield return "Karczew (MZ)";
            //yield return "Kargowa (LS)";
            //yield return "Karlino (ZP)";
            //yield return "Karpacz (DŚ)";
            //yield return "Kartuzy (PM)";
            //yield return "Katowice (ŚL)";
            //yield return "Kazimierz Dolny (LB)";
            //yield return "Kazimierza Wielka (ŚK)";
            //yield return "Kąty Wrocławskie (DŚ)";
            //yield return "Kcynia (KP)";
            //yield return "Kędzierzyn-Koźle (OP)";
            //yield return "Kępice (PM)";
            //yield return "Kępno (WP)";
            //yield return "Kętrzyn (WM)";
            //yield return "Kęty (MP)";
            //yield return "Kielce (ŚK)";
            //yield return "Kietrz (OP)";
            //yield return "Kisielice (WM)";
            //yield return "Kleczew (WP)";
            //yield return "Kleszczele (PL)";
            //yield return "Kluczbork (OP)";
            //yield return "Kłecko (WP)";
            //yield return "Kłobuck (ŚL)";
            //yield return "Kłodawa (WP)";
            //yield return "Kłodzko (DŚ)";
            //yield return "Knurów (ŚL)";
            //yield return "Knyszyn (PL)";
            //yield return "Kobylin (WP)";
            //yield return "Kobyłka (MZ)";
            //yield return "Kock (LB)";
            //yield return "Kolbuszowa (PK)";
            //yield return "Kolno (PL)";
            //yield return "Kolonowskie (OP)";
            //yield return "Koluszki (ŁD)";
            //yield return "Kołaczyce (PK)";
            //yield return "Koło (WP)";
            //yield return "Kołobrzeg (ZP)";
            //yield return "Koniecpol (ŚL)";
            //yield return "Konin (WP)";
            //yield return "Konstancin-Jeziorna (MZ)";
            //yield return "Konstantynów Łódzki (ŁD)";
            //yield return "Końskie (ŚK)";
            //yield return "Koprzywnica (ŚK)";
            //yield return "Korfantów (OP)";
            //yield return "Koronowo (KP)";
            //yield return "Korsze (WM)";
            //yield return "Kosów Lacki (MZ)";
            //yield return "Kostrzyn (WP)";
            //yield return "Kostrzyn nad Odrą (LS)";
            //yield return "Koszalin (ZP)";
            //yield return "Kościan (WP)";
            //yield return "Kościerzyna (PM)";
            //yield return "Kowal (KP)";
            //yield return "Kowalewo Pomorskie (KP)";
            //yield return "Kowary (DŚ)";
            //yield return "Koziegłowy (ŚL)";
            //yield return "Kozienice (MZ)";
            //yield return "Koźmin Wielkopolski (WP)";
            //yield return "Kożuchów (LS)";
            //yield return "Kórnik (WP)";
            //yield return "Krajenka (WP)";
            //yield return "Kraków (MP)";
            //yield return "Krapkowice (OP)";
            //yield return "Krasnobród (LB)";
            //yield return "Krasnystaw (LB)";
            //yield return "Kraśnik (LB)";
            //yield return "Krobia (WP)";
            //yield return "Krosno (PK)";
            //yield return "Krosno Odrzańskie (LS)";
            //yield return "Krośniewice (ŁD)";
            //yield return "Krotoszyn (WP)";
            //yield return "Kruszwica (KP)";
            //yield return "Krynica Morska (PM)";
            //yield return "Krynica-Zdrój (MP)";
            //yield return "Krynki (PL)";
            //yield return "Krzanowice (ŚL)";
            //yield return "Krzepice (ŚL)";
            //yield return "Krzeszowice (MP)";
            //yield return "Krzywiń (WP)";
            //yield return "Krzyż Wielkopolski (WP)";
            //yield return "Książ Wielkopolski (WP)";
            //yield return "Kudowa-Zdrój (DŚ)";
            //yield return "Kunów (ŚK)";
            //yield return "Kutno (ŁD)";
            //yield return "Kuźnia Raciborska (ŚL)";
            //yield return "Kwidzyn (PM)";
            //yield return "Lądek-Zdrój (DŚ)";
            //yield return "Legionowo (MZ)";
            //yield return "Legnica (DŚ)";
            //yield return "Lesko (PK)";
            //yield return "Leszno (WP)";
            //yield return "Leśna (DŚ)";
            //yield return "Leśnica (OP)";
            //yield return "Lewin Brzeski (OP)";
            //yield return "Leżajsk (PK)";
            //yield return "Lębork (PM)";
            //yield return "Lędziny (ŚL)";
            //yield return "Libiąż (MP)";
            //yield return "Lidzbark (WM)";
            //yield return "Lidzbark Warmiński (WM)";
            //yield return "Limanowa (MP)";
            //yield return "Lipiany (ZP)";
            //yield return "Lipno (KP)";
            //yield return "Lipsk (PL)";
            //yield return "Lipsko (MZ)";
            //yield return "Lubaczów (PK)";
            //yield return "Lubań (DŚ)";
            //yield return "Lubartów (LB)";
            //yield return "Lubawa (WM)";
            //yield return "Lubawka (DŚ)";
            //yield return "Lubień Kujawski (KP)";
            //yield return "Lubin (DŚ)";
            //yield return "Lublin (LB)";
            //yield return "Lubliniec (ŚL)";
            //yield return "Lubniewice (LS)";
            //yield return "Lubomierz (DŚ)";
            //yield return "Luboń (WP)";
            //yield return "Lubraniec (KP)";
            //yield return "Lubsko (LS)";
            //yield return "Lwówek (WP)";
            //yield return "Lwówek Śląski (DŚ)";
            //yield return "Łabiszyn (KP)";
            //yield return "Łańcut (PK)";
            //yield return "Łapy (PL)";
            //yield return "Łasin (KP)";
            //yield return "Łask (ŁD)";
            //yield return "Łaskarzew (MZ)";
            //yield return "Łaszczów (LB)";
            //yield return "Łaziska Górne (ŚL)";
            //yield return "Łazy (ŚL)";
            //yield return "Łeba (PM)";
            //yield return "Łęczna (LB)";
            //yield return "Łęczyca (ŁD)";
            //yield return "Łęknica (LS)";
            //yield return "Łobez (ZP)";
            //yield return "Łobżenica (WP)";
            //yield return "Łochów (MZ)";
            //yield return "Łomianki (MZ)";
            //yield return "Łomża (PL)";
            //yield return "Łosice (MZ)";
            //yield return "Łowicz (ŁD)";
            //yield return "Łódź (ŁD)";
            //yield return "Łuków (LB)";
            //yield return "Maków Mazowiecki (MZ)";
            //yield return "Maków Podhalański (MP)";
            //yield return "Malbork (PM)";
            //yield return "Małogoszcz (ŚK)";
            //yield return "Małomice (LS)";
            //yield return "Margonin (WP)";
            //yield return "Marki (MZ)";
            //yield return "Maszewo (ZP)";
            //yield return "Miasteczko Śląskie (ŚL)";
            //yield return "Miastko (PM)";
            //yield return "Michałowo (PL)";
            //yield return "Miechów (MP)";
            //yield return "Miejska Górka (WP)";
            //yield return "Mielec (PK)";
            //yield return "Mieroszów (DŚ)";
            //yield return "Mieszkowice (ZP)";
            //yield return "Międzybórz (DŚ)";
            //yield return "Międzychód (WP)";
            //yield return "Międzylesie (DŚ)";
            //yield return "Międzyrzec Podlaski (LB)";
            //yield return "Międzyrzecz (LS)";
            //yield return "Międzyzdroje (ZP)";
            //yield return "Mikołajki (WM)";
            //yield return "Mikołów (ŚL)";
            //yield return "Mikstat (WP)";
            //yield return "Milanówek (MZ)";
            //yield return "Milicz (DŚ)";
            //yield return "Miłakowo (WM)";
            //yield return "Miłomłyn (WM)";
            //yield return "Miłosław (WP)";
            //yield return "Mińsk Mazowiecki (MZ)";
            //yield return "Mirosławiec (ZP)";
            //yield return "Mirsk (DŚ)";
            //yield return "Mława (MZ)";
            //yield return "Młynary (WM)";
            //yield return "Mogielnica (MZ)";
            //yield return "Mogilno (KP)";
            //yield return "Mońki (PL)";
            //yield return "Morąg (WM)";
            //yield return "Mordy (MZ)";
            //yield return "Moryń (ZP)";
            //yield return "Mosina (WP)";
            //yield return "Mrągowo (WM)";
            //yield return "Mrocza (KP)";
            //yield return "Mszana Dolna (MP)";
            //yield return "Mszczonów (MZ)";
            //yield return "Murowana Goślina (WP)";
            //yield return "Muszyna (MP)";
            //yield return "Mysłowice (ŚL)";
            //yield return "Myszków (ŚL)";
            //yield return "Myszyniec (MZ)";
            //yield return "Myślenice (MP)";
            //yield return "Myślibórz (ZP)";
            //yield return "Nakło nad Notecią (KP)";
            //yield return "Nałęczów (LB)";
            //yield return "Namysłów (OP)";
            //yield return "Narol (PK)";
            //yield return "Nasielsk (MZ)";
            //yield return "Nekla (WP)";
            //yield return "Nidzica (WM)";
            //yield return "Niemcza (DŚ)";
            //yield return "Niemodlin (OP)";
            //yield return "Niepołomice (MP)";
            //yield return "Nieszawa (KP)";
            //yield return "Nisko (PK)";
            //yield return "Nowa Dęba (PK)";
            //yield return "Nowa Ruda (DŚ)";
            //yield return "Nowa Sarzyna (PK)";
            //yield return "Nowa Sól (LS)";
            //yield return "Nowe (KP)";
            //yield return "Nowe Brzesko (MP)";
            //yield return "Nowe Miasteczko (LS)";
            //yield return "Nowe Miasto Lubawskie (WM)";
            //yield return "Nowe Miasto nad Pilicą (MZ";
            //yield return "Nowe Skalmierzyce (WP)";
            //yield return "Nowe Warpno (ZP)";
            //yield return "Nowogard (ZP)";
            //yield return "Nowogrodziec (DŚ)";
            //yield return "Nowogród (PL)";
            //yield return "Nowogród Bobrzański (LS)";
            //yield return "Nowy Dwór Gdański (PM)";
            //yield return "Nowy Dwór Mazowiecki (MZ)";
            //yield return "Nowy Sącz (MP)";
            //yield return "Nowy Staw (PM)";
            //yield return "Nowy Targ (MP)";
            //yield return "Nowy Tomyśl (WP)";
            //yield return "Nowy Wiśnicz (MP)";
            //yield return "Nysa (OP)";
            //yield return "Oborniki (WP)";
            //yield return "Oborniki Śląskie (DŚ)";
            //yield return "Obrzycko (WP)";
            //yield return "Odolanów (WP)";
            //yield return "Ogrodzieniec (ŚL)";
            //yield return "Okonek (WP)";
            //yield return "Olecko (WM)";
            //yield return "Olesno (OP)";
            //yield return "Oleszyce (PK)";
            //yield return "Oleśnica (DŚ)";
            //yield return "Olkusz (MP)";
            //yield return "Olsztyn (WM)";
            //yield return "Olsztynek (WM)";
            //yield return "Olszyna (DŚ)";
            //yield return "Oława (DŚ)";
            //yield return "Opalenica (WP)";
            //yield return "Opatów (ŚK)";
            //yield return "Opoczno (ŁD)";
            //yield return "Opole (OP)";
            //yield return "Opole Lubelskie (LB)";
            //yield return "Orneta (WM)";
            //yield return "Orzesze (ŚL)";
            //yield return "Orzysz (WM)";
            //yield return "Osieczna (WP)";
            //yield return "Osiek (ŚK)";
            //yield return "Ostrołęka (MZ)";
            //yield return "Ostroróg (WP)";
            //yield return "Ostrowiec Świętokrzyski (Ś";
            //yield return "Ostróda (WM)";
            //yield return "Ostrów Lubelski (LB)";
            //yield return "Ostrów Mazowiecka (MZ)";
            //yield return "Ostrów Wielkopolski (WP)";
            //yield return "Ostrzeszów (WP)";
            //yield return "Ośno Lubuskie (LS)";
            //yield return "Oświęcim (MP)";
            //yield return "Otmuchów (OP)";
            //yield return "Otwock (MZ)";
            //yield return "Ozimek (OP)";
            //yield return "Ozorków (ŁD)";
            //yield return "Ożarów (ŚK)";
            //yield return "Ożarów Mazowiecki (MZ)";
            //yield return "Pabianice (ŁD)";
            //yield return "Paczków (OP)";
            //yield return "Pajęczno (ŁD)";
            //yield return "Pakość (KP)";
            //yield return "Parczew (LB)";
            //yield return "Pasłęk (WM)";
            //yield return "Pasym (WM)";
            //yield return "Pelplin (PM)";
            //yield return "Pełczyce (ZP)";
            //yield return "Piaseczno (MZ)";
            //yield return "Piaski (LB)";
            //yield return "Piastów (MZ)";
            //yield return "Piechowice (DŚ)";
            //yield return "Piekary Śląskie (ŚL)";
            //yield return "Pieniężno (WM)";
            //yield return "Pieńsk (DŚ)";
            //yield return "Pieszyce (DŚ)";
            //yield return "Pilawa (MZ)";
            //yield return "Pilica (ŚL)";
            //yield return "Pilzno (PK)";
            //yield return "Piła (WP)";
            //yield return "Piława Górna (DŚ)";
            //yield return "Pińczów (ŚK)";
            //yield return "Pionki (MZ)";
            //yield return "Piotrków Kujawski (KP)";
            //yield return "Piotrków Trybunalski (ŁD)";
            //yield return "Pisz (WM)";
            //yield return "Piwniczna-Zdrój (MP)";
            //yield return "Pleszew (WP)";
            //yield return "Płock (MZ)";
            //yield return "Płońsk (MZ)";
            //yield return "Płoty (ZP)";
            //yield return "Pniewy (WP)";
            //yield return "Pobiedziska (WP)";
            //yield return "Poddębice (ŁD)";
            //yield return "Podkowa Leśna (MZ)";
            //yield return "Pogorzela (WP)";
            //yield return "Polanica-Zdrój (DŚ)";
            //yield return "Polanów (ZP)";
            //yield return "Police (ZP)";
            //yield return "Polkowice (DŚ)";
            //yield return "Połaniec (ŚK)";
            //yield return "Połczyn-Zdrój (ZP)";
            //yield return "Poniatowa (LB)";
            //yield return "Poniec (WP)";
            //yield return "Poręba (ŚL)";
            //yield return "Poznań (WP)";
            //yield return "Prabuty (PM)";
            //yield return "Praszka (OP)";
            //yield return "Prochowice (DŚ)";
            //yield return "Proszowice (MP)";
            //yield return "Prószków (OP)";
            //yield return "Pruchnik (PK)";
            //yield return "Prudnik (OP)";
            //yield return "Prusice (DŚ)";
            //yield return "Pruszcz Gdański (PM)";
            //yield return "Pruszków (MZ)";
            //yield return "Przasnysz (MZ)";
            //yield return "Przecław (PK)";
            //yield return "Przedbórz (ŁD)";
            //yield return "Przedecz (WP)";
            //yield return "Przemków (DŚ)";
            //yield return "Przemyśl (PK)";
            //yield return "Przeworsk (PK)";
            //yield return "Przysucha (MZ)";
            //yield return "Pszczyna (ŚL)";
            //yield return "Pszów (ŚL)";
            //yield return "Puck (PM)";
            //yield return "Puławy (LB)";
            //yield return "Pułtusk (MZ)";
            //yield return "Puszczykowo (WP)";
            //yield return "Pyrzyce (ZP)";
            //yield return "Pyskowice (ŚL)";
            //yield return "Pyzdry (WP)";
            //yield return "Rabka-Zdrój (MP)";
            //yield return "Raciąż (MZ)";
            //yield return "Racibórz (ŚL)";
            //yield return "Radków (DŚ)";
            //yield return "Radlin (ŚL)";
            //yield return "Radłów (MP)";
            //yield return "Radom (MZ)";
            //yield return "Radomsko (ŁD)";
            //yield return "Radomyśl Wielki (PK)";
            //yield return "Radymno (PK)";
            //yield return "Radziejów (KP)";
            //yield return "Radzionków (ŚL)";
            //yield return "Radzymin (MZ)";
            //yield return "Radzyń Chełmiński (KP)";
            //yield return "Radzyń Podlaski (LB)";
            //yield return "Rajgród (PL)";
            //yield return "Rakoniewice (WP)";
            //yield return "Raszków (WP)";
            //yield return "Rawa Mazowiecka (ŁD)";
            //yield return "Rawicz (WP)";
            //yield return "Recz (ZP)";
            //yield return "Reda (PM)";
            //yield return "Rejowiec Fabryczny (LB)";
            //yield return "Resko (ZP)";
            //yield return "Reszel (WM)";
            //yield return "Rogoźno (WP)";
            //yield return "Ropczyce (PK)";
            //yield return "Różan (MZ)";
            //yield return "Ruciane-Nida (WM)";
            //yield return "Ruda Śląska (ŚL)";
            //yield return "Rudnik nad Sanem (PK)";
            //yield return "Rumia (PM)";
            //yield return "Rybnik (ŚL)";
            //yield return "Rychwał (WP)";
            //yield return "Rydułtowy (ŚL)";
            //yield return "Rydzyna (WP)";
            //yield return "Ryglice (MP)";
            //yield return "Ryki (LB)";
            //yield return "Rymanów (PK)";
            //yield return "Ryn (WM)";
            //yield return "Rypin (KP)";
            //yield return "Rzepin (LS)";
            //yield return "Rzeszów (PK)";
            //yield return "Rzgów (ŁD)";
            //yield return "Sandomierz (ŚK)";
            //yield return "Sanok (PK)";
            //yield return "Sejny (PL)";
            //yield return "Serock (MZ)";
            //yield return "Sędziszów (ŚK)";
            //yield return "Sędziszów Małopolski (PK)";
            //yield return "Sępopol (WM)";
            //yield return "Sępólno Krajeńskie (KP)";
            //yield return "Sianów (ZP)";
            //yield return "Siechnice (DŚ)";
            //yield return "Siedlce (MZ)";
            //yield return "Siemianowice Śląskie (ŚL)";
            //yield return "Siemiatycze (PL)";
            //yield return "Sieniawa (PK)";
            //yield return "Sieradz (ŁD)";
            //yield return "Sieraków (WP)";
            //yield return "Sierpc (MZ)";
            //yield return "Siewierz (ŚL)";
            //yield return "Skalbmierz (ŚK)";
            //yield return "Skała (MP)";
            //yield return "Skarszewy (PM)";
            //yield return "Skaryszew (MZ)";
            //yield return "Skarżysko-Kamienna (ŚK)";
            //yield return "Skawina (MP)";
            //yield return "Skępe (KP)";
            //yield return "Skierniewice (ŁD)";
            //yield return "Skoczów (ŚL)";
            //yield return "Skoki (WP)";
            //yield return "Skórcz (PM)";
            //yield return "Skwierzyna (LS)";
            //yield return "Sława (LS)";
            //yield return "Sławków (ŚL)";
            //yield return "Sławno (ZP)";
            //yield return "Słomniki (MP)";
            //yield return "Słubice (LS)";
            //yield return "Słupca (WP)";
            //yield return "Słupsk (PM)";
            //yield return "Sobótka (DŚ)";
            //yield return "Sochaczew (MZ)";
            //yield return "Sokołów Małopolski (PK)";
            //yield return "Sokołów Podlaski (MZ)";
            //yield return "Sokółka (PL)";
            //yield return "Solec Kujawski (KP)";
            //yield return "Sompolno (WP)";
            //yield return "Sopot (PM)";
            //yield return "Sosnowiec (ŚL)";
            //yield return "Sośnicowice (ŚL)";
            //yield return "Stalowa Wola (PK)";
            //yield return "Starachowice (ŚK)";
            //yield return "Stargard Szczeciński (ZP)";
            //yield return "Starogard Gdański (PM)";
            //yield return "Stary Sącz (MP)";
            //yield return "Staszów (ŚK)";
            //yield return "Stawiski (PL)";
            //yield return "Stawiszyn (WP)";
            //yield return "Stąporków (ŚK)";
            //yield return "Stęszew (WP)";
            //yield return "Stoczek Łukowski (LB)";
            //yield return "Stronie Śląskie (DŚ)";
            //yield return "Strumień (ŚL)";
            //yield return "Stryków (ŁD)";
            //yield return "Strzegom (DŚ)";
            //yield return "Strzelce Krajeńskie (LS)";
            //yield return "Strzelce Opolskie (OP)";
            //yield return "Strzelin (DŚ)";
            //yield return "Strzelno (KP)";
            //yield return "Strzyżów (PK)";
            //yield return "Sucha Beskidzka (MP)";
            //yield return "Suchań (ZP)";
            //yield return "Suchedniów (ŚK)";
            //yield return "Suchowola (PL)";
            //yield return "Sulechów (LS)";
            //yield return "Sulejów (ŁD)";
            //yield return "Sulejówek (MZ)";
            //yield return "Sulęcin (LS)";
            //yield return "Sulmierzyce (WP)";
            //yield return "Sułkowice (MP)";
            //yield return "Supraśl (PL)";
            //yield return "Suraż (PL)";
            //yield return "Susz (WM)";
            //yield return "Suwałki (PL)";
            //yield return "Swarzędz (WP)";
            //yield return "Syców (DŚ)";
            //yield return "Szadek (ŁD)";
            //yield return "Szamocin (WP)";
            //yield return "Szamotuły (WP)";
            //yield return "Szczawnica (MP)";
            //yield return "Szczawno-Zdrój (DŚ)";
            //yield return "Szczebrzeszyn (LB)";
            //yield return "Szczecin (ZP)";
            //yield return "Szczecinek (ZP)";
            //yield return "Szczekociny (ŚL)";
            //yield return "Szczucin (MP)";
            //yield return "Szczuczyn (PL)";
            //yield return "Szczyrk (ŚL)";
            //yield return "Szczytna (DŚ)";
            //yield return "Szczytno (WM)";
            //yield return "Szepietowo (PL)";
            //yield return "Szklarska Poręba (DŚ)";
            //yield return "Szlichtyngowa (LS)";
            //yield return "Szprotawa (LS)";
            //yield return "Sztum (PM)";
            //yield return "Szubin (KP)";
            //yield return "Szydłowiec (MZ)";
            //yield return "Ś[edytuj]";
            //yield return "Ścinawa (DŚ)";
            //yield return "Ślesin (WP)";
            //yield return "Śmigiel (WP)";
            //yield return "Śrem (WP)";
            //yield return "Środa Śląska (DŚ)";
            //yield return "Środa Wielkopolska (WP)";
            //yield return "Świątniki Górne (MP)";
            //yield return "Świdnica (DŚ)";
            //yield return "Świdnik (LB)";
            //yield return "Świdwin (ZP)";
            //yield return "Świebodzice (DŚ)";
            //yield return "Świebodzin (LS)";
            //yield return "Świecie (KP)";
            //yield return "Świeradów-Zdrój (DŚ)";
            //yield return "Świerzawa (DŚ)";
            //yield return "Świętochłowice (ŚL)";
            //yield return "Świnoujście (ZP)";
            //yield return "Tarczyn (MZ)";
            //yield return "Tarnobrzeg (PK)";
            //yield return "Tarnogród (LB)";
            //yield return "Tarnowskie Góry (ŚL)";
            //yield return "Tarnów (MP)";
            //yield return "Tczew (PM)";
            //yield return "Terespol (LB)";
            //yield return "Tłuszcz (MZ)";
            //yield return "Tolkmicko (WM)";
            //yield return "Tomaszów Lubelski (LB)";
            //yield return "Tomaszów Mazowiecki (ŁD)";
            //yield return "Toruń (KP)";
            //yield return "Torzym (LS)";
            //yield return "Toszek (ŚL)";
            //yield return "Trzcianka (WP)";
            //yield return "Trzciel (LS)";
            //yield return "Trzcińsko-Zdrój (ZP)";
            //yield return "Trzebiatów (ZP)";
            //yield return "Trzebinia (MP)";
            //yield return "Trzebnica (DŚ)";
            //yield return "Trzemeszno (WP)";
            //yield return "Tuchola (KP)";
            //yield return "Tuchów (MP)";
            //yield return "Tuczno (ZP)";
            //yield return "Tuliszków (WP)";
            //yield return "Turek (WP)";
            //yield return "Tuszyn (ŁD)";
            //yield return "Twardogóra (DŚ)";
            //yield return "Tychowo (ZP)";
            //yield return "Tychy (ŚL)";
            //yield return "Tyczyn (PK)";
            //yield return "Tykocin (PL)";
            //yield return "Tyszowce (LB)";
            //yield return "Ujazd (OP)";
            //yield return "Ujście (WP)";
            //yield return "Ulanów (PK)";
            //yield return "Uniejów (ŁD)";
            //yield return "Ustka (PM)";
            //yield return "Ustroń (ŚL)";
            //yield return "Ustrzyki Dolne (PK)";
            //yield return "Wadowice (MP)";
            //yield return "Wałbrzych (DŚ)";
            //yield return "Wałcz (ZP)";
            //yield return "Warka (MZ)";
            //yield return "Warszawa (MZ)";
            //yield return "Warta (ŁD)";
            //yield return "Wasilków (PL)";
            //yield return "Wąbrzeźno (KP)";
            //yield return "Wąchock (ŚK)";
            //yield return "Wągrowiec (WP)";
            //yield return "Wąsosz (DŚ)";
            //yield return "Wejherowo (PM)";
            //yield return "Węgliniec (DŚ)";
            //yield return "Węgorzewo (WM)";
            //yield return "Węgorzyno (ZP)";
            //yield return "Węgrów (MZ)";
            //yield return "Wiązów (DŚ)";
            //yield return "Wieleń (WP)";
            //yield return "Wielichowo (WP)";
            //yield return "Wieliczka (MP)";
            //yield return "Wieluń (ŁD)";
            //yield return "Wieruszów (ŁD)";
            //yield return "Więcbork (KP)";
            //yield return "Wilamowice (ŚL)";
            //yield return "Wisła (ŚL)";
            //yield return "Witkowo (WP)";
            //yield return "Witnica (LS)";
            //yield return "Wleń (DŚ)";
            //yield return "Władysławowo (PM)";
            //yield return "Włocławek (KP)";
            //yield return "Włodawa (LB)";
            //yield return "Włoszczowa (ŚK)";
            //yield return "Wodzisław Śląski (ŚL)";
            //yield return "Wojcieszów (DŚ)";
            //yield return "Wojkowice (ŚL)";
            //yield return "Wojnicz (MP)";
            //yield return "Wolbórz (ŁD)";
            //yield return "Wolbrom (MP)";
            //yield return "Wolin (ZP)";
            //yield return "Wolsztyn (WP)";
            //yield return "Wołczyn (OP)";
            //yield return "Wołomin (MZ)";
            //yield return "Wołów (DŚ)";
            //yield return "Woźniki (ŚL)";
            //yield return "Wrocław (DŚ)";
            //yield return "Wronki (WP)";
            //yield return "Września (WP)";
            //yield return "Wschowa (LS)";
            //yield return "Wyrzysk (WP)";
            //yield return "Wysoka (WP)";
            //yield return "Wysokie Mazowieckie (PL)";
            //yield return "Wyszków (MZ)";
            //yield return "Wyszogród (MZ)";
            //yield return "Wyśmierzyce (MZ)";
            //yield return "Zabłudów (PL)";
            //yield return "Zabrze (ŚL)";
            //yield return "Zagórów (WP)";
            //yield return "Zagórz (PK)";
            //yield return "Zakliczyn (MP)";
            //yield return "Zakopane (MP)";
            //yield return "Zakroczym (MZ)";
            //yield return "Zalewo (WM)";
            //yield return "Zambrów (PL)";
            //yield return "Zamość (LB)";
            //yield return "Zator (MP)";
            //yield return "Zawadzkie (OP)";
            //yield return "Zawichost (ŚK)";
            //yield return "Zawidów (DŚ)";
            //yield return "Zawiercie (ŚL)";
            //yield return "Ząbki (MZ)";
            //yield return "Ząbkowice Śląskie (DŚ)";
            //yield return "Zbąszynek (LS)";
            //yield return "Zbąszyń (WP)";
            //yield return "Zduny (WP)";
            //yield return "Zduńska Wola (ŁD)";
            //yield return "Zdzieszowice (OP)";
            //yield return "Zelów (ŁD)";
            //yield return "Zgierz (ŁD)";
            //yield return "Zgorzelec (DŚ)";
            //yield return "Zielona Góra (LS)";
            //yield return "Zielonka (MZ)";
            //yield return "Ziębice (DŚ)";
            //yield return "Złocieniec (ZP)";
            //yield return "Złoczew (ŁD)";
            //yield return "Złotoryja (DŚ)";
            //yield return "Złotów (WP)";
            //yield return "Złoty Stok (DŚ)";
            //yield return "Zwierzyniec (LB)";
            //yield return "Zwoleń (MZ)";
            //yield return "Żabno (MP)";
            //yield return "Żagań (LS)";
            //yield return "Żarki (ŚL)";
            //yield return "Żarów (DŚ)";
            //yield return "Żary (LS)";
            //yield return "Żelechów (MZ)";
            //yield return "Żerków (WP)";
            //yield return "Żmigród (DŚ)";
            //yield return "Żnin (KP)";
            //yield return "Żory (ŚL)";
            //yield return "Żukowo (PM)";
            //yield return "Żuromin (MZ)";
            //yield return "Żychlin (ŁD)";
            //yield return "Żyrardów (MZ)";
            //yield return "Żywiec (ŚL)";

        }
    }
}